# Generated by Django 3.2 on 2021-05-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flip',
            field=models.IntegerField(),
        ),
    ]
