# Generated by Django 3.2 on 2021-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatuser',
            name='bg_color',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='fg_color',
            field=models.CharField(max_length=8),
        ),
    ]
