# Generated by Django 3.1.7 on 2021-05-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('webex_img', models.ImageField(upload_to='webex/')),
                ('coins', models.IntegerField()),
                ('game_clear', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('nickname', models.CharField(max_length=20)),
                ('webex_img', models.ImageField(upload_to='webex/')),
                ('profile_img', models.ImageField(upload_to='profile/')),
                ('name_img', models.ImageField(upload_to='name/')),
                ('card_img', models.ImageField(upload_to='card/')),
                ('flag', models.BooleanField()),
                ('song', models.CharField(max_length=50)),
                ('song_url', models.CharField(max_length=100)),
                ('git_url', models.CharField(blank=True, max_length=100)),
                ('insta_url', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ssafy5_3.student')),
            ],
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssafy5_3.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('from_msg', models.ManyToManyField(related_name='to_msg', to='ssafy5_3.Student')),
            ],
        ),
    ]
