# Generated by Django 3.2 on 2021-04-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssafy5_3', '0002_auto_20210430_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(upload_to='ssafy5_3/static/profile/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='webex_img',
            field=models.ImageField(upload_to='ssafy5_3/static/webex/'),
        ),
    ]
