# Generated by Django 3.2 on 2021-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssafy5_3', '0004_auto_20210430_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='webex_img',
            field=models.ImageField(upload_to='webex/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='webex_img',
            field=models.ImageField(upload_to='webex/'),
        ),
    ]
